kind: Deployment
apiVersion: apps/v1
metadata:
  name: counter-postgresadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-postgresadmin
  template:
    metadata:
      labels:
        app: counter-postgresadmin
    spec:
      containers:
        - name: counter-postgresadmin
          image: >-
            docker.io/thajeztah/pgadmin4
          ports:
            - containerPort: 5050
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
